- .eslintignore
- .eslintrc.json
- .eslintrc.yml
- app/models/pregnancy-center-history.js
- app/models/pregnancy-center.js
- data/data.js
- package.json
- server/server.js
-Add eslint package, configuration file, and ignore file (remove current unused configuration)
-Fix files that have lint errors
-Add npm commands to run linter
**To run:**
There are 2 different npm commands you can run to run the linter.
1. `npm run lint` will run the linter on the entire repo (excluding the ignored files)
2. `npm run lint-path path_to_file_or_directory` will run the linter for the directory or file that you specify
> Add linter functionality with eslint

- server/persons/schema/mongoose-schema.js
- server/pregnancy-centers/schema/joi-schema.js
- server/pregnancy-centers/schema/mongoose-schema.js
Added PersonSchema, changed PrimaryContactUserId to PrimaryContactPersonId
No tests yet.
> Added PersonSchema

- server/data-import/test/test.js
- server/persons/schema/mongoose-schema.js
- server/pregnancy-centers/schema/joi-schema.js
- server/pregnancy-centers/schema/mongoose-schema.js
- server/users/schema/mongoose-schema.js
changes `services` to use an object rather than an array, changes `name` to `prcName`, removes pregnancy-center-level email address, builds on the new `Persons` Collection to use it for `primaryContactPersonId`
Uncomment the test.js file and run using `yarn test`.
> Pregnancy center updates

- CONTRIBUTING.md
This updates the install instructions to match what exactly was useful. 
no tests necessary
> Update to installation instructions for macOS

- server/data-import/data.js
In data importing route correction
> data route correction

- .travis.yml
- SETUP.md
- package.json
This upgrades Node to the latest version, 10.4.0.
To update your local machine:
`nvm install 10.4.0`
`nvm use 10.4.0`
`nvm alias default node`
`yarn test` after install
> Upgrade to 10.4.0

- server/pregnancy-centers/schema/joi-schema.js
- server/pregnancy-centers/schema/mongoose-schema.js
- server/test/pregnancy-center-tests.js
This adds the` hotlinePhoneNumber` field to the backend, with the same schema as the regular `phone` field. 
Tests were added to the test suite, so `yarn test` can be run.
> change schemas to include hotlinePhoneNumber, add tests.

- client/js/components/breakpoints.js
- client/js/mini-app/header.js
- client/js/mini-app/view.js
This is a work in progress as we're still finalizing the designs, but I wanted to add a header that sort of resembles what the final result will be. 
1. Go to http://localhost:4000/mini-app
1. The header should look like this:
> Add a header to the mini app

- client/js/mini-app/form.js
- client/js/mini-app/view.js
This is a work in progress as we're still finalizing the designs. 
I just added a few small tweaks to the address input and added a super simple footer.
1. Go to http://localhost:4000/mini-app
1. The address input and footer should look like this:
> Tweak the address input and add a footer

- client/js/components/button.js
- client/js/hah-app/reducers.js
- client/js/verification-portal/components/header-modal.js
- client/js/verification-portal/pregnancy-resource-center/action-creators.js
- client/js/verification-portal/pregnancy-resource-center/form.js
- client/js/verification-portal/pregnancy-resource-center/view.js
This PR disables the Save button while the form is submitting. It's important that we do that so that you can't click Submit multiple times while the form is submitting. I also made a couple of refactors. I tried to comment directly on the changed lines to explain some of the changes.
1. Load the PRC form
1. Click Verify Next Resource
1. Click Save Progress
1. See that the form is disabled (meaning you can't click it again) and that opacity changes to 50% and the cursor is an "in progress" cursor
> Disable Save button on submit

- client/js/verification-portal/components/services-group.js
- client/js/verification-portal/pregnancy-resource-center/form.js
- client/js/verification-portal/pregnancy-resource-center/services.js
Updated toggles for Services and Hours to align properly with headings. Aligned the Services fields with the Services heading.
Toggle buttons work as expected.
> Change layout to have toggles align with headings, align services fields

- server/data-import/geocode.js
This just adds an if clause to check whether the call to geocode an address has any results. 
`yarn geocode`
> change geocode so that it doesn't error if there are no results

- client/js/hah-app/app.js
- client/js/hah-app/landing.js
- client/js/verification-portal/index.js
- public/index.html
- Background image of the landing page is set.
- verification portal background color is set to white to hide the image portion 
- run yarn webpack and visit the http://localhost:4000/
- see the image, it is full page background
- click the link to verification portal, it will appear as before no change.
> Backgroung image

- client/js/authentication/facebook-login-button/view.js
- client/js/authentication/login-button.js
- client/js/verification-portal/resource-view.js
Remove login button from form page, add login button to landing page. Edit styling per Invision design.
Logging in using FB button works as expected.
> FB login button

- client/js/mini-app/home-page-banner.js
- client/js/mini-app/questions/index.js
- client/js/mini-app/view.js
Adds this banner on the homepage:
1. Look at the homepage and see that the banner matches the designs
1. Resize the browser to a mobile size and see that the banner disappears
> Add home page banner

- package.json
- yarn.lock
The package `axios` has a high severity security risk with the version we're on. This PR upgrades the package to the latest version to address the security vulnerability.
Make sure the app still works.
> Upgrade axios to latest version

- client/js/components/breakpoints.js
- client/js/hah-app/about.js
- client/js/hah-app/feedback.js
- client/js/hah-app/team-member.js
- client/js/mini-app/components/button.js
- client/js/mini-app/components/footer.js
- client/js/mini-app/components/input.js
- client/js/mini-app/form.js
- client/js/mini-app/header.js
- client/js/mini-app/logo-and-navigation.js
- client/js/mini-app/questions/index.js
- client/js/mini-app/questions/instruction.js
- client/js/mini-app/questions/no-results.js
- client/js/mini-app/questions/resource-carousel.js
We decided that it's necessary to have an additional tablet view size. This will allow us to be able to make a more responsive site. This PR just adds the additional size parameters for tablet and adds the additional code to make sure the site still works for the tablet size. 
Note: As of this PR, the tablet view will still be the same as desktop. In future PRs, we'll update the tablet view according to design changes.
No visible changes were made so just go to the review app (link below) and make sure all existing functionality is still there.
> Add size parameters for tablet

- server/test/fqhc-tests.js
- server/test/pregnancy-center-tests.js
- server/util/util.js
A test was failing because the promises for creating histories wasn't being handled correctly.
rebuild repeatedly on TravisCI - tests were not failing locally, so testing locally will not actually test this change.
> Unskip test '/PUT /api/fqhcs/:fqhcId'

- client/js/mini-app/questions/index.js
- client/js/mini-app/questions/instruction.js
- client/js/mini-app/questions/resource-carousel.js
- client/js/mini-app/questions/step-two.js
Add the back button on the search card
Designs: https://projects.invisionapp.com/d/main#/console/15837992/328667322/preview
> Add back button

- package.json
- yarn.lock
Upgrade `moment` to a version that doesn't have a security vulnerability.
> Upgrade moment

- package.json
- server/data-import/overwrite-fqhc-data.js
- server/data-import/overwrite-pc-data.js
- yarn.lock
Update mongodb EJSON. This is only used to import new data from files, which I don't think we're using now, so I didn't do testing for it, but I added a note about EJSON in case there is trouble importing in the future. 
N/A
> update mongodb EJSON

- .travis.yml
- SETUP.md
- package.json
Upgrade node to the latest LTS version -> 10.16.3
In order to update your local environment:
```
nvm install 10.16.3
nvm alias default 10.16.3
nvm use default
brew install yarn --ignore-dependencies
yarn install
```
Everything should still work the same.
> Upgrade node to 10.16.3

- client/js/components/icons/icon-components/hospital-icon.js
- client/js/components/icons/icon-components/pregnancy-icon.js
- client/js/components/icons/svgs/hospital.svg
- client/js/components/icons/svgs/pregnancy.svg
- client/js/mini-app/questions/resource-carousel.js
Cleanup the CHC and PRC buttons and disable the CHC button for now.
> Resource Button Cleanup

- client/js/components/scroll-to-top.js
- client/js/hah-app/about.js
- client/js/hah-app/emergency/index.js
- client/js/hah-app/feedback.js
- client/js/hah-app/router.js
- client/js/mini-app/view.js
Add component so that the scroll is reset to the top of the page when you go to a new page.
> Add Scroll to Top component

- client/js/hah-app/about.js
- client/js/hah-app/emergency/index.js
- client/js/hah-app/emergency/resource-card.js
- client/js/hah-app/feedback.js
- client/js/hah-app/landing.js
- client/js/hah-app/team-member.js
- client/js/mini-app/components/button.js
- client/js/mini-app/components/footer.js
- client/js/mini-app/components/input.js
- client/js/mini-app/components/menu.js
- client/js/mini-app/home-page-banner.js
- client/js/mini-app/logo-and-navigation.js
- client/js/mini-app/questions/instruction.js
- client/js/mini-app/questions/resource-carousel.js
Make the font size changes, per design recommendations
1. Anything 18px, make 16px
2. Anything 24 px, make 20px
3. Anything 30 px, make 24px
> Font size changes

- package.json
- yarn.lock
> Upgrade passport

- client/js/hah-app/about.js
- client/js/hah-app/emergency/index.js
- client/js/hah-app/emergency/resource-card.js
- client/js/hah-app/feedback.js
- client/js/hah-app/team-member.js
- client/js/mini-app/components/button.js
- client/js/mini-app/components/footer.js
- client/js/mini-app/components/input.js
- client/js/mini-app/form.js
- client/js/mini-app/home-page-banner.js
- client/js/mini-app/questions/index.js
- client/js/mini-app/questions/instruction.js
- client/js/mini-app/questions/no-results.js
- client/js/mini-app/questions/step-two.js
We added another breakpoint for "big phone" - this adds all the components for all the views
> Add BigPhone components for all views

- server/server.js
Compression, baby. The site is sooo slow right now lol
> Add express compression

- client/js/verification-portal/components/get-resource-to-verify-button.js
- client/js/verification-portal/components/header-modal.js
- client/js/verification-portal/pregnancy-resource-center/action-creators.js
- client/js/verification-portal/pregnancy-resource-center/form.js
Ok so some changes were made in [this PR](https://github.com/helpassisther/help-assist-her/pull/130) to disable the `Save` button while the verification form is submitting.
Then [this PR](https://github.com/helpassisther/help-assist-her/pull/109) made additional changes that ended up reverting some of the changes in the above PR and thus breaking the submit on the form.
I reverted the breaking changes so the form is able to submit successfully now.
I also removed and/or commented out all of the fields except for the first section because we have  decided that we're only going to be verifying those fields for now.
Play around with the verification form and make sure that data is able to be submitted successfully.
> Fix prc form

- client/js/mini-app/form.js
- client/js/mini-app/home-page-banner.js
- client/js/mini-app/questions/index.js
- client/js/mini-app/questions/instruction.js
- client/js/mini-app/questions/resource-carousel.js
- client/js/mini-app/questions/step-two.js
Marylouise and I got together again and made pixel perfect changes to the homepage.
> Pixel Perfect

- client/js/mini-app/components/input.js
- client/js/mini-app/form.js
- client/js/mini-app/questions/step-two.js
- public/index.html
Things were showing up funky on mobile devices (see this [Trello card](https://trello.com/c/oDGafDSU/80-bug-the-styling-of-step-two-looks-funny-on-mobile))
This PR fixes those issues.
> Iphone Tweaks

- client/js/hah-app/about.js
- client/js/mini-app/components/button.js
- client/js/mini-app/questions/no-results.js
- client/js/mini-app/questions/resource-card.js
- client/js/mini-app/questions/resource-list.js
> Design Part 4

- server/pregnancy-centers/queries.js
- server/routes/api/pregnancy-centers.js
- server/scripts/clear-verified-data-field.js
- server/test/pregnancy-centers/near-me-tests.js
1. Add a script to remove the `verifiedData` field so that all records can be verified again
2. Update the date to only show results verified after 12-01-19
> Update verified date

- client/js/verification-portal/pregnancy-resource-center/form.js
- client/js/verification-portal/util.js
> Fix phone number validation

- server/test/fqhcs/fqhc-tests.js
- server/test/pregnancy-centers/pregnancy-center-tests.js
These tests randomly started failing on master after no changes were made. They passed 4 months ago when the last change was made. Going to skip them for now, until we can fix them.
> Skip randomly failing tests for now

- client/js/verification-portal/community-health-center/form.js
- client/js/verification-portal/community-health-center/requests.js
- server/routes/api/fqhcs.js
Update the FE code so `verifiedData` is also being sent in the request to add a new CHC. 
Also added the scaffolding for the new endpoint so the request is actually successful (though it's not implemented)
> Add new CHC

- client/js/components/toggle-formik.js
- client/js/verification-portal/community-health-center/form.js
- client/js/verification-portal/community-health-center/requests.js
- client/js/verification-portal/community-health-center/validate.js
- package.json
- yarn.lock
- Add validation for all fields in the form
- Reset the values in the form to their original state (clear them) if the submit was successful
> Add validation

- .github/workflows/ci.yml
- client/Router.js
- client/components/LogoAndNavigation.js
- client/components/NoResultsPage.js
- client/components/ScrollToTop.js
- client/components/SearchForm.js
_Remove this and add a detailed description of the changes that were made._
_Remove this and add a test plan that the reviewer can use to test your changes._
> feat: remove miniapp route prefix
